import { type FunctionReference, anyApi } from "convex/server";
import { type GenericId as Id } from "convex/values";

export const api: PublicApiType = anyApi as unknown as PublicApiType;
export const internal: InternalApiType = anyApi as unknown as InternalApiType;

export type PublicApiType = {
  v1: {
    auth: {
      mutation: {
        sendAuthOtp: FunctionReference<
          "mutation",
          "public",
          { email: string },
          any
        >;
        signInWithOtp: FunctionReference<
          "mutation",
          "public",
          { email: string; otp: string },
          any
        >;
        refreshAuthSession: FunctionReference<
          "mutation",
          "public",
          { sessionId: Id<"sessions"> },
          any
        >;
        logout: FunctionReference<"mutation", "public", any, any>;
      };
    };
    design: {
      mutation: {
        updateDesignById: FunctionReference<
          "mutation",
          "public",
          {
            designId: Id<"designs">;
            updates: {
              description?: string;
              floorPlanFile?: { mediaType: string; url: string };
              floorPlanUrl?: string;
              generatingFurnitureRecommendation?: boolean;
              inspirationImageUrl?: string;
              name?: string;
              productCategories?: Array<
                | "Arm Chair"
                | "Artwork"
                | "Baking Dish"
                | "Bamboo Flooring"
                | "Bar Cart"
                | "Bar Stool"
                | "Bar Table"
                | "Bath Linens"
                | "Bathroom Accessories"
                | "Bed"
                | "Bedding"
                | "Bedroom Vanity"
                | "Bench"
                | "Blind"
                | "Bookcase"
                | "Bowl"
                | "Broom"
                | "Brush"
                | "Cabinet"
                | "Can Opener"
                | "Carpet"
                | "Ceiling Lamp"
                | "Ceiling Mirror"
                | "Chaise Lounge"
                | "Chest"
                | "Coat Rack"
                | "Coffee Maker"
                | "Coffee Table"
                | "Colander"
                | "Concrete Flooring"
                | "Console Table"
                | "Cookie Sheet"
                | "Cookware"
                | "Cork Flooring"
                | "Corkscrew"
                | "Counter"
                | "Counter Stool"
                | "Cup"
                | "Curtain"
                | "Curtain Panels"
                | "Curtain Rod"
                | "Cutting Board"
                | "Desk"
                | "Desk Chair"
                | "Dining Chair"
                | "Dining Table"
                | "Dinnerware"
                | "Dresser"
                | "Dustpan"
                | "Engineered Wood"
                | "Entry Hook"
                | "Fixture"
                | "Floor Lamp"
                | "Fork"
                | "Grater"
                | "Hair Dryer"
                | "Hanger"
                | "Hardwood Flooring"
                | "Head Board"
                | "Iron"
                | "Ironing Board"
                | "Kettle"
                | "King Mattress"
                | "Kitchen Tool"
                | "Knife"
                | "Ladle"
                | "Laminate Flooring"
                | "Linoleum"
                | "Loveseat"
                | "Nightstand"
                | "Ottoman"
                | "Pancake Turner"
                | "Pendant Light"
                | "Pillow"
                | "Pitcher"
                | "Plant"
                | "Planter"
                | "Plate"
                | "Plunger"
                | "Potholder"
                | "Pots & Vases"
                | "Queen Mattress"
                | "Rack"
                | "Roast Pan"
                | "Rug"
                | "Rug Pad"
                | "Salad Plate"
                | "Salt & Pepper Shaker"
                | "Sconce"
                | "Screen"
                | "Sculpture"
                | "Sectional"
                | "Shelf"
                | "Shelving Unit"
                | "Side Table"
                | "Sideboard"
                | "Silverware Tray"
                | "Skillet"
                | "Small Appliance"
                | "Sofa"
                | "Sofa Bed"
                | "Sound Machine"
                | "Soup Bowl"
                | "Speaker Dock"
                | "Spoon"
                | "Standing Mirror"
                | "Stands"
                | "Stone Flooring"
                | "Storage Cabinet"
                | "Table Lamp"
                | "Tablecloth"
                | "Throw Blanket"
                | "Throw Pillow"
                | "Tile"
                | "Toaster"
                | "Tongs"
                | "Towel"
                | "Tray"
                | "Tumbler"
                | "TV"
                | "TV Media Console"
                | "TV Wall Mount"
                | "Twin Mattress"
                | "Utensils"
                | "Vanity"
                | "Vanity Light"
                | "Vegetable Peeler"
                | "Vinyl Flooring"
                | "Wall Mirror"
                | "Wallpaper"
                | "Wardrobe"
                | "Waste basket"
                | "Whisk"
                | "Wine Glass"
                | "Outdoor  Arm Chair"
                | "Outdoor  Rug"
                | "Outdoor  Dining Chair"
                | "Outdoor Chair"
                | "Outdoor Coffee Table"
                | "Outdoor Dining Table"
                | "Outdoor Fire Pit"
                | "Outdoor Lounger"
                | "Outdoor Side Table"
                | "Outdoor Sofa"
                | "Outdoor Throw Pillow"
                | "Outdoor Umbrella"
              >;
              productIds?: Array<Id<"products">>;
              renderedImageUrl?: string;
              renderingImage?: boolean;
              spaceType?:
                | "Attic"
                | "Basement"
                | "Bathroom"
                | "Bedroom"
                | "Classroom"
                | "Dining Room"
                | "Entryway"
                | "Event Space"
                | "Exercise Room"
                | "Kitchen"
                | "Laundry Room"
                | "Library"
                | "Living Room"
                | "Lobby"
                | "Locker Room"
                | "Lounge"
                | "Media Room"
                | "Medical Room"
                | "Meeting Room"
                | "Mudroom"
                | "Office"
                | "Outdoor Space"
                | "Spa"
                | "Walk-in Closet";
              styles?: Array<
                | "Art Deco"
                | "Biophilic"
                | "Bohemian"
                | "Brutalism"
                | "Coastal"
                | "Colonial"
                | "Contemporary"
                | "Craftsman"
                | "Eclectic"
                | "French Country"
                | "Hollywood Glamour"
                | "Industrial"
                | "Japandi"
                | "Luxury"
                | "Maximalist"
                | "Mediterranean"
                | "Mid-Century Modern"
                | "Minimalist"
                | "Modern"
                | "Modern Farmhouse"
                | "Neoclassical"
                | "Neutral"
                | "Rustic"
                | "Scandinavian"
                | "Shabby Chic"
                | "Southwestern"
                | "Traditional"
                | "Transitional"
                | "Tudor"
                | "Victorian"
                | "Vintage"
              >;
              tags?: Array<string>;
            };
            workspaceId: Id<"workspaces">;
          },
          any
        >;
        addNewProductToDesignById: FunctionReference<
          "mutation",
          "public",
          {
            designId: Id<"designs">;
            update: {
              productCategory:
                | "Arm Chair"
                | "Artwork"
                | "Baking Dish"
                | "Bamboo Flooring"
                | "Bar Cart"
                | "Bar Stool"
                | "Bar Table"
                | "Bath Linens"
                | "Bathroom Accessories"
                | "Bed"
                | "Bedding"
                | "Bedroom Vanity"
                | "Bench"
                | "Blind"
                | "Bookcase"
                | "Bowl"
                | "Broom"
                | "Brush"
                | "Cabinet"
                | "Can Opener"
                | "Carpet"
                | "Ceiling Lamp"
                | "Ceiling Mirror"
                | "Chaise Lounge"
                | "Chest"
                | "Coat Rack"
                | "Coffee Maker"
                | "Coffee Table"
                | "Colander"
                | "Concrete Flooring"
                | "Console Table"
                | "Cookie Sheet"
                | "Cookware"
                | "Cork Flooring"
                | "Corkscrew"
                | "Counter"
                | "Counter Stool"
                | "Cup"
                | "Curtain"
                | "Curtain Panels"
                | "Curtain Rod"
                | "Cutting Board"
                | "Desk"
                | "Desk Chair"
                | "Dining Chair"
                | "Dining Table"
                | "Dinnerware"
                | "Dresser"
                | "Dustpan"
                | "Engineered Wood"
                | "Entry Hook"
                | "Fixture"
                | "Floor Lamp"
                | "Fork"
                | "Grater"
                | "Hair Dryer"
                | "Hanger"
                | "Hardwood Flooring"
                | "Head Board"
                | "Iron"
                | "Ironing Board"
                | "Kettle"
                | "King Mattress"
                | "Kitchen Tool"
                | "Knife"
                | "Ladle"
                | "Laminate Flooring"
                | "Linoleum"
                | "Loveseat"
                | "Nightstand"
                | "Ottoman"
                | "Pancake Turner"
                | "Pendant Light"
                | "Pillow"
                | "Pitcher"
                | "Plant"
                | "Planter"
                | "Plate"
                | "Plunger"
                | "Potholder"
                | "Pots & Vases"
                | "Queen Mattress"
                | "Rack"
                | "Roast Pan"
                | "Rug"
                | "Rug Pad"
                | "Salad Plate"
                | "Salt & Pepper Shaker"
                | "Sconce"
                | "Screen"
                | "Sculpture"
                | "Sectional"
                | "Shelf"
                | "Shelving Unit"
                | "Side Table"
                | "Sideboard"
                | "Silverware Tray"
                | "Skillet"
                | "Small Appliance"
                | "Sofa"
                | "Sofa Bed"
                | "Sound Machine"
                | "Soup Bowl"
                | "Speaker Dock"
                | "Spoon"
                | "Standing Mirror"
                | "Stands"
                | "Stone Flooring"
                | "Storage Cabinet"
                | "Table Lamp"
                | "Tablecloth"
                | "Throw Blanket"
                | "Throw Pillow"
                | "Tile"
                | "Toaster"
                | "Tongs"
                | "Towel"
                | "Tray"
                | "Tumbler"
                | "TV"
                | "TV Media Console"
                | "TV Wall Mount"
                | "Twin Mattress"
                | "Utensils"
                | "Vanity"
                | "Vanity Light"
                | "Vegetable Peeler"
                | "Vinyl Flooring"
                | "Wall Mirror"
                | "Wallpaper"
                | "Wardrobe"
                | "Waste basket"
                | "Whisk"
                | "Wine Glass"
                | "Outdoor  Arm Chair"
                | "Outdoor  Rug"
                | "Outdoor  Dining Chair"
                | "Outdoor Chair"
                | "Outdoor Coffee Table"
                | "Outdoor Dining Table"
                | "Outdoor Fire Pit"
                | "Outdoor Lounger"
                | "Outdoor Side Table"
                | "Outdoor Sofa"
                | "Outdoor Throw Pillow"
                | "Outdoor Umbrella";
              productId: Id<"products">;
            };
            workspaceId: Id<"workspaces">;
          },
          any
        >;
        removeProductFromDesignById: FunctionReference<
          "mutation",
          "public",
          {
            designId: Id<"designs">;
            remove: {
              productCategory:
                | "Arm Chair"
                | "Artwork"
                | "Baking Dish"
                | "Bamboo Flooring"
                | "Bar Cart"
                | "Bar Stool"
                | "Bar Table"
                | "Bath Linens"
                | "Bathroom Accessories"
                | "Bed"
                | "Bedding"
                | "Bedroom Vanity"
                | "Bench"
                | "Blind"
                | "Bookcase"
                | "Bowl"
                | "Broom"
                | "Brush"
                | "Cabinet"
                | "Can Opener"
                | "Carpet"
                | "Ceiling Lamp"
                | "Ceiling Mirror"
                | "Chaise Lounge"
                | "Chest"
                | "Coat Rack"
                | "Coffee Maker"
                | "Coffee Table"
                | "Colander"
                | "Concrete Flooring"
                | "Console Table"
                | "Cookie Sheet"
                | "Cookware"
                | "Cork Flooring"
                | "Corkscrew"
                | "Counter"
                | "Counter Stool"
                | "Cup"
                | "Curtain"
                | "Curtain Panels"
                | "Curtain Rod"
                | "Cutting Board"
                | "Desk"
                | "Desk Chair"
                | "Dining Chair"
                | "Dining Table"
                | "Dinnerware"
                | "Dresser"
                | "Dustpan"
                | "Engineered Wood"
                | "Entry Hook"
                | "Fixture"
                | "Floor Lamp"
                | "Fork"
                | "Grater"
                | "Hair Dryer"
                | "Hanger"
                | "Hardwood Flooring"
                | "Head Board"
                | "Iron"
                | "Ironing Board"
                | "Kettle"
                | "King Mattress"
                | "Kitchen Tool"
                | "Knife"
                | "Ladle"
                | "Laminate Flooring"
                | "Linoleum"
                | "Loveseat"
                | "Nightstand"
                | "Ottoman"
                | "Pancake Turner"
                | "Pendant Light"
                | "Pillow"
                | "Pitcher"
                | "Plant"
                | "Planter"
                | "Plate"
                | "Plunger"
                | "Potholder"
                | "Pots & Vases"
                | "Queen Mattress"
                | "Rack"
                | "Roast Pan"
                | "Rug"
                | "Rug Pad"
                | "Salad Plate"
                | "Salt & Pepper Shaker"
                | "Sconce"
                | "Screen"
                | "Sculpture"
                | "Sectional"
                | "Shelf"
                | "Shelving Unit"
                | "Side Table"
                | "Sideboard"
                | "Silverware Tray"
                | "Skillet"
                | "Small Appliance"
                | "Sofa"
                | "Sofa Bed"
                | "Sound Machine"
                | "Soup Bowl"
                | "Speaker Dock"
                | "Spoon"
                | "Standing Mirror"
                | "Stands"
                | "Stone Flooring"
                | "Storage Cabinet"
                | "Table Lamp"
                | "Tablecloth"
                | "Throw Blanket"
                | "Throw Pillow"
                | "Tile"
                | "Toaster"
                | "Tongs"
                | "Towel"
                | "Tray"
                | "Tumbler"
                | "TV"
                | "TV Media Console"
                | "TV Wall Mount"
                | "Twin Mattress"
                | "Utensils"
                | "Vanity"
                | "Vanity Light"
                | "Vegetable Peeler"
                | "Vinyl Flooring"
                | "Wall Mirror"
                | "Wallpaper"
                | "Wardrobe"
                | "Waste basket"
                | "Whisk"
                | "Wine Glass"
                | "Outdoor  Arm Chair"
                | "Outdoor  Rug"
                | "Outdoor  Dining Chair"
                | "Outdoor Chair"
                | "Outdoor Coffee Table"
                | "Outdoor Dining Table"
                | "Outdoor Fire Pit"
                | "Outdoor Lounger"
                | "Outdoor Side Table"
                | "Outdoor Sofa"
                | "Outdoor Throw Pillow"
                | "Outdoor Umbrella";
              productId: Id<"products">;
            };
            workspaceId: Id<"workspaces">;
          },
          any
        >;
        addTagsToDesign: FunctionReference<
          "mutation",
          "public",
          {
            designId: Id<"designs">;
            tagNames: Array<string>;
            workspaceId: Id<"workspaces">;
          },
          any
        >;
        deleteDesignTag: FunctionReference<
          "mutation",
          "public",
          { designTagId: Id<"designTags">; workspaceId: Id<"workspaces"> },
          any
        >;
      };
      query: {
        getDesignDataByChatId: FunctionReference<
          "query",
          "public",
          { chatId: Id<"chats"> },
          any
        >;
        getDesignsByWorkspaceId: FunctionReference<
          "query",
          "public",
          { workspaceId: Id<"workspaces"> },
          any
        >;
        getUniqueDesignSpacesForWorkspace: FunctionReference<
          "query",
          "public",
          { workspaceId: Id<"workspaces"> },
          any
        >;
        getDesignTagsForWorkspace: FunctionReference<
          "query",
          "public",
          { workspaceId: Id<"workspaces"> },
          any
        >;
      };
    };
    product: {
      mutation: {
        createProduct: FunctionReference<
          "mutation",
          "public",
          {
            data: {
              brand?: string;
              category: string;
              colorNames?: Array<string>;
              currencyCode:
                | "AED"
                | "AFN"
                | "ALL"
                | "AMD"
                | "ANG"
                | "AOA"
                | "ARS"
                | "AUD"
                | "AWG"
                | "AZN"
                | "BAM"
                | "BBD"
                | "BDT"
                | "BGN"
                | "BHD"
                | "BIF"
                | "BMD"
                | "BND"
                | "BOB"
                | "BOV"
                | "BRL"
                | "BSD"
                | "BTN"
                | "BWP"
                | "BYN"
                | "BZD"
                | "CAD"
                | "CDF"
                | "CHE"
                | "CHF"
                | "CHW"
                | "CLF"
                | "CLP"
                | "CNY"
                | "COP"
                | "COU"
                | "CRC"
                | "CUC"
                | "CUP"
                | "CVE"
                | "CZK"
                | "DJF"
                | "DKK"
                | "DOP"
                | "DZD"
                | "EGP"
                | "ERN"
                | "ETB"
                | "EUR"
                | "FJD"
                | "FKP"
                | "GBP"
                | "GEL"
                | "GHS"
                | "GIP"
                | "GMD"
                | "GNF"
                | "GTQ"
                | "GYD"
                | "HKD"
                | "HNL"
                | "HTG"
                | "HUF"
                | "IDR"
                | "ILS"
                | "INR"
                | "IQD"
                | "IRR"
                | "ISK"
                | "JMD"
                | "JOD"
                | "JPY"
                | "KES"
                | "KGS"
                | "KHR"
                | "KMF"
                | "KPW"
                | "KRW"
                | "KWD"
                | "KYD"
                | "KZT"
                | "LAK"
                | "LBP"
                | "LKR"
                | "LRD"
                | "LSL"
                | "LYD"
                | "MAD"
                | "MDL"
                | "MGA"
                | "MKD"
                | "MMK"
                | "MNT"
                | "MOP"
                | "MRU"
                | "MUR"
                | "MVR"
                | "MWK"
                | "MXN"
                | "MXV"
                | "MYR"
                | "MZN"
                | "NAD"
                | "NGN"
                | "NIO"
                | "NOK"
                | "NPR"
                | "NZD"
                | "OMR"
                | "PAB"
                | "PEN"
                | "PGK"
                | "PHP"
                | "PKR"
                | "PLN"
                | "PYG"
                | "QAR"
                | "RON"
                | "RSD"
                | "RUB"
                | "RWF"
                | "SAR"
                | "SBD"
                | "SCR"
                | "SDG"
                | "SEK"
                | "SGD"
                | "SHP"
                | "SLE"
                | "SOS"
                | "SRD"
                | "SSP"
                | "STN"
                | "SVC"
                | "SYP"
                | "SZL"
                | "THB"
                | "TJS"
                | "TMT"
                | "TND"
                | "TOP"
                | "TRY"
                | "TTD"
                | "TWD"
                | "TZS"
                | "UAH"
                | "UGX"
                | "USD"
                | "USN"
                | "UYI"
                | "UYU"
                | "UYW"
                | "UZS"
                | "VED"
                | "VES"
                | "VND"
                | "VUV"
                | "WST"
                | "XAF"
                | "XAG"
                | "XAU"
                | "XBA"
                | "XBB"
                | "XBC"
                | "XBD"
                | "XCD"
                | "XDR"
                | "XOF"
                | "XPD"
                | "XPF"
                | "XPT"
                | "XSU"
                | "XTS"
                | "XUA"
                | "XXX"
                | "YER"
                | "ZAR"
                | "ZMW"
                | "ZWG";
              depth: number;
              description: string;
              dimension?: string;
              dimensionUnit: "in";
              fhSku: string;
              gtin?: string;
              height: number;
              hexColors?: Array<string>;
              imageEmbedding: Array<number>;
              imageUrls: Array<string>;
              itemId?: string;
              ludwigImageUrl: string;
              mainImageUrl?: string;
              map?: number;
              materials: Array<string>;
              mpn?: string;
              msrp?: number;
              name: string;
              ownerId?: Id<"workspaces">;
              pId: string;
              pdpLink?: string;
              restockDate?: number;
              retailPrice: number;
              shippingCountryCodes: Array<
                | "AF"
                | "AL"
                | "DZ"
                | "AS"
                | "AD"
                | "AO"
                | "AI"
                | "AQ"
                | "AG"
                | "AR"
                | "AM"
                | "AW"
                | "AU"
                | "AT"
                | "AZ"
                | "BS"
                | "BH"
                | "BD"
                | "BB"
                | "BY"
                | "BE"
                | "BZ"
                | "BJ"
                | "BM"
                | "BT"
                | "BO"
                | "BQ"
                | "BA"
                | "BW"
                | "BV"
                | "BR"
                | "IO"
                | "BN"
                | "BG"
                | "BF"
                | "BI"
                | "CV"
                | "KH"
                | "CM"
                | "CA"
                | "KY"
                | "CF"
                | "TD"
                | "CL"
                | "CN"
                | "CX"
                | "CC"
                | "CO"
                | "KM"
                | "CD"
                | "CG"
                | "CK"
                | "CR"
                | "HR"
                | "CU"
                | "CW"
                | "CY"
                | "CZ"
                | "CI"
                | "DK"
                | "DJ"
                | "DM"
                | "DO"
                | "EC"
                | "EG"
                | "SV"
                | "GQ"
                | "ER"
                | "EE"
                | "SZ"
                | "ET"
                | "FK"
                | "FO"
                | "FJ"
                | "FI"
                | "FR"
                | "GF"
                | "PF"
                | "TF"
                | "GA"
                | "GM"
                | "GE"
                | "DE"
                | "GH"
                | "GI"
                | "GR"
                | "GL"
                | "GD"
                | "GP"
                | "GU"
                | "GT"
                | "GG"
                | "GN"
                | "GW"
                | "GY"
                | "HT"
                | "HM"
                | "VA"
                | "HN"
                | "HK"
                | "HU"
                | "IS"
                | "IN"
                | "ID"
                | "IR"
                | "IQ"
                | "IE"
                | "IM"
                | "IL"
                | "IT"
                | "JM"
                | "JP"
                | "JE"
                | "JO"
                | "KZ"
                | "KE"
                | "KI"
                | "KP"
                | "KR"
                | "KW"
                | "KG"
                | "LA"
                | "LV"
                | "LB"
                | "LS"
                | "LR"
                | "LY"
                | "LI"
                | "LT"
                | "LU"
                | "MO"
                | "MG"
                | "MW"
                | "MY"
                | "MV"
                | "ML"
                | "MT"
                | "MH"
                | "MQ"
                | "MR"
                | "MU"
                | "YT"
                | "MX"
                | "FM"
                | "MD"
                | "MC"
                | "MN"
                | "ME"
                | "MS"
                | "MA"
                | "MZ"
                | "MM"
                | "NA"
                | "NR"
                | "NP"
                | "NL"
                | "NC"
                | "NZ"
                | "NI"
                | "NE"
                | "NG"
                | "NU"
                | "NF"
                | "MK"
                | "MP"
                | "NO"
                | "OM"
                | "PK"
                | "PW"
                | "PS"
                | "PA"
                | "PG"
                | "PY"
                | "PE"
                | "PH"
                | "PN"
                | "PL"
                | "PT"
                | "PR"
                | "QA"
                | "RO"
                | "RU"
                | "RW"
                | "RE"
                | "BL"
                | "SH"
                | "KN"
                | "LC"
                | "MF"
                | "PM"
                | "VC"
                | "WS"
                | "SM"
                | "ST"
                | "SA"
                | "SN"
                | "RS"
                | "SC"
                | "SL"
                | "SG"
                | "SX"
                | "SK"
                | "SI"
                | "SB"
                | "SO"
                | "ZA"
                | "GS"
                | "SS"
                | "ES"
                | "LK"
                | "SD"
                | "SR"
                | "SJ"
                | "SE"
                | "CH"
                | "SY"
                | "TW"
                | "TJ"
                | "TZ"
                | "TH"
                | "TL"
                | "TG"
                | "TK"
                | "TO"
                | "TT"
                | "TN"
                | "TR"
                | "TM"
                | "TC"
                | "TV"
                | "UG"
                | "UA"
                | "AE"
                | "GB"
                | "UM"
                | "US"
                | "UY"
                | "UZ"
                | "VU"
                | "VE"
                | "VN"
                | "VG"
                | "VI"
                | "WF"
                | "EH"
                | "YE"
                | "ZM"
                | "ZW"
                | "AX"
                | "EU"
              >;
              shippingDepth: number;
              shippingDimension?: string;
              shippingHeight: number;
              shippingPrice?: number;
              shippingWeight: number;
              shippingWidth: number;
              sku: string;
              stockQty: number;
              styles: Array<
                | "Art Deco"
                | "Biophilic"
                | "Bohemian"
                | "Brutalism"
                | "Coastal"
                | "Colonial"
                | "Contemporary"
                | "Craftsman"
                | "Eclectic"
                | "French Country"
                | "Hollywood Glamour"
                | "Industrial"
                | "Japandi"
                | "Luxury"
                | "Maximalist"
                | "Mediterranean"
                | "Mid-Century Modern"
                | "Minimalist"
                | "Modern"
                | "Modern Farmhouse"
                | "Neoclassical"
                | "Neutral"
                | "Rustic"
                | "Scandinavian"
                | "Shabby Chic"
                | "Southwestern"
                | "Traditional"
                | "Transitional"
                | "Tudor"
                | "Victorian"
                | "Vintage"
              >;
              textEmbedding: Array<number>;
              tradePrice: number;
              unitPerBox: number;
              vendorId: Id<"productVendors">;
              warehouseCountryCodes: Array<
                | "AF"
                | "AL"
                | "DZ"
                | "AS"
                | "AD"
                | "AO"
                | "AI"
                | "AQ"
                | "AG"
                | "AR"
                | "AM"
                | "AW"
                | "AU"
                | "AT"
                | "AZ"
                | "BS"
                | "BH"
                | "BD"
                | "BB"
                | "BY"
                | "BE"
                | "BZ"
                | "BJ"
                | "BM"
                | "BT"
                | "BO"
                | "BQ"
                | "BA"
                | "BW"
                | "BV"
                | "BR"
                | "IO"
                | "BN"
                | "BG"
                | "BF"
                | "BI"
                | "CV"
                | "KH"
                | "CM"
                | "CA"
                | "KY"
                | "CF"
                | "TD"
                | "CL"
                | "CN"
                | "CX"
                | "CC"
                | "CO"
                | "KM"
                | "CD"
                | "CG"
                | "CK"
                | "CR"
                | "HR"
                | "CU"
                | "CW"
                | "CY"
                | "CZ"
                | "CI"
                | "DK"
                | "DJ"
                | "DM"
                | "DO"
                | "EC"
                | "EG"
                | "SV"
                | "GQ"
                | "ER"
                | "EE"
                | "SZ"
                | "ET"
                | "FK"
                | "FO"
                | "FJ"
                | "FI"
                | "FR"
                | "GF"
                | "PF"
                | "TF"
                | "GA"
                | "GM"
                | "GE"
                | "DE"
                | "GH"
                | "GI"
                | "GR"
                | "GL"
                | "GD"
                | "GP"
                | "GU"
                | "GT"
                | "GG"
                | "GN"
                | "GW"
                | "GY"
                | "HT"
                | "HM"
                | "VA"
                | "HN"
                | "HK"
                | "HU"
                | "IS"
                | "IN"
                | "ID"
                | "IR"
                | "IQ"
                | "IE"
                | "IM"
                | "IL"
                | "IT"
                | "JM"
                | "JP"
                | "JE"
                | "JO"
                | "KZ"
                | "KE"
                | "KI"
                | "KP"
                | "KR"
                | "KW"
                | "KG"
                | "LA"
                | "LV"
                | "LB"
                | "LS"
                | "LR"
                | "LY"
                | "LI"
                | "LT"
                | "LU"
                | "MO"
                | "MG"
                | "MW"
                | "MY"
                | "MV"
                | "ML"
                | "MT"
                | "MH"
                | "MQ"
                | "MR"
                | "MU"
                | "YT"
                | "MX"
                | "FM"
                | "MD"
                | "MC"
                | "MN"
                | "ME"
                | "MS"
                | "MA"
                | "MZ"
                | "MM"
                | "NA"
                | "NR"
                | "NP"
                | "NL"
                | "NC"
                | "NZ"
                | "NI"
                | "NE"
                | "NG"
                | "NU"
                | "NF"
                | "MK"
                | "MP"
                | "NO"
                | "OM"
                | "PK"
                | "PW"
                | "PS"
                | "PA"
                | "PG"
                | "PY"
                | "PE"
                | "PH"
                | "PN"
                | "PL"
                | "PT"
                | "PR"
                | "QA"
                | "RO"
                | "RU"
                | "RW"
                | "RE"
                | "BL"
                | "SH"
                | "KN"
                | "LC"
                | "MF"
                | "PM"
                | "VC"
                | "WS"
                | "SM"
                | "ST"
                | "SA"
                | "SN"
                | "RS"
                | "SC"
                | "SL"
                | "SG"
                | "SX"
                | "SK"
                | "SI"
                | "SB"
                | "SO"
                | "ZA"
                | "GS"
                | "SS"
                | "ES"
                | "LK"
                | "SD"
                | "SR"
                | "SJ"
                | "SE"
                | "CH"
                | "SY"
                | "TW"
                | "TJ"
                | "TZ"
                | "TH"
                | "TL"
                | "TG"
                | "TK"
                | "TO"
                | "TT"
                | "TN"
                | "TR"
                | "TM"
                | "TC"
                | "TV"
                | "UG"
                | "UA"
                | "AE"
                | "GB"
                | "UM"
                | "US"
                | "UY"
                | "UZ"
                | "VU"
                | "VE"
                | "VN"
                | "VG"
                | "VI"
                | "WF"
                | "EH"
                | "YE"
                | "ZM"
                | "ZW"
                | "AX"
                | "EU"
              >;
              weight: number;
              weightUnit: "lb";
              width: number;
            };
            poApiKey: string;
          },
          any
        >;
      };
      vendor: {
        mutation: {
          createVendor: FunctionReference<
            "mutation",
            "public",
            {
              data: { name: string; r2FolderId: string; vId: string };
              poApiKey: string;
            },
            any
          >;
        };
      };
      query: {
        getPoProductByPId: FunctionReference<
          "query",
          "public",
          { pId: string; poApiKey: string },
          any
        >;
        getProductCategoriesForSpace: FunctionReference<
          "query",
          "public",
          {
            spaceType:
              | "Attic"
              | "Basement"
              | "Bathroom"
              | "Bedroom"
              | "Classroom"
              | "Dining Room"
              | "Entryway"
              | "Event Space"
              | "Exercise Room"
              | "Kitchen"
              | "Laundry Room"
              | "Library"
              | "Living Room"
              | "Lobby"
              | "Locker Room"
              | "Lounge"
              | "Media Room"
              | "Medical Room"
              | "Meeting Room"
              | "Mudroom"
              | "Office"
              | "Outdoor Space"
              | "Spa"
              | "Walk-in Closet";
          },
          any
        >;
        getClientProductsWithFilters: FunctionReference<
          "query",
          "public",
          {
            paginationOptions?: { cursor?: string; numItems?: number };
            productFilter?: {
              availability?: "In Stock" | "Low Stock" | "Out of Stock";
              brand?: string;
              category?:
                | "Arm Chair"
                | "Artwork"
                | "Baking Dish"
                | "Bamboo Flooring"
                | "Bar Cart"
                | "Bar Stool"
                | "Bar Table"
                | "Bath Linens"
                | "Bathroom Accessories"
                | "Bed"
                | "Bedding"
                | "Bedroom Vanity"
                | "Bench"
                | "Blind"
                | "Bookcase"
                | "Bowl"
                | "Broom"
                | "Brush"
                | "Cabinet"
                | "Can Opener"
                | "Carpet"
                | "Ceiling Lamp"
                | "Ceiling Mirror"
                | "Chaise Lounge"
                | "Chest"
                | "Coat Rack"
                | "Coffee Maker"
                | "Coffee Table"
                | "Colander"
                | "Concrete Flooring"
                | "Console Table"
                | "Cookie Sheet"
                | "Cookware"
                | "Cork Flooring"
                | "Corkscrew"
                | "Counter"
                | "Counter Stool"
                | "Cup"
                | "Curtain"
                | "Curtain Panels"
                | "Curtain Rod"
                | "Cutting Board"
                | "Desk"
                | "Desk Chair"
                | "Dining Chair"
                | "Dining Table"
                | "Dinnerware"
                | "Dresser"
                | "Dustpan"
                | "Engineered Wood"
                | "Entry Hook"
                | "Fixture"
                | "Floor Lamp"
                | "Fork"
                | "Grater"
                | "Hair Dryer"
                | "Hanger"
                | "Hardwood Flooring"
                | "Head Board"
                | "Iron"
                | "Ironing Board"
                | "Kettle"
                | "King Mattress"
                | "Kitchen Tool"
                | "Knife"
                | "Ladle"
                | "Laminate Flooring"
                | "Linoleum"
                | "Loveseat"
                | "Nightstand"
                | "Ottoman"
                | "Pancake Turner"
                | "Pendant Light"
                | "Pillow"
                | "Pitcher"
                | "Plant"
                | "Planter"
                | "Plate"
                | "Plunger"
                | "Potholder"
                | "Pots & Vases"
                | "Queen Mattress"
                | "Rack"
                | "Roast Pan"
                | "Rug"
                | "Rug Pad"
                | "Salad Plate"
                | "Salt & Pepper Shaker"
                | "Sconce"
                | "Screen"
                | "Sculpture"
                | "Sectional"
                | "Shelf"
                | "Shelving Unit"
                | "Side Table"
                | "Sideboard"
                | "Silverware Tray"
                | "Skillet"
                | "Small Appliance"
                | "Sofa"
                | "Sofa Bed"
                | "Sound Machine"
                | "Soup Bowl"
                | "Speaker Dock"
                | "Spoon"
                | "Standing Mirror"
                | "Stands"
                | "Stone Flooring"
                | "Storage Cabinet"
                | "Table Lamp"
                | "Tablecloth"
                | "Throw Blanket"
                | "Throw Pillow"
                | "Tile"
                | "Toaster"
                | "Tongs"
                | "Towel"
                | "Tray"
                | "Tumbler"
                | "TV"
                | "TV Media Console"
                | "TV Wall Mount"
                | "Twin Mattress"
                | "Utensils"
                | "Vanity"
                | "Vanity Light"
                | "Vegetable Peeler"
                | "Vinyl Flooring"
                | "Wall Mirror"
                | "Wallpaper"
                | "Wardrobe"
                | "Waste basket"
                | "Whisk"
                | "Wine Glass"
                | "Outdoor  Arm Chair"
                | "Outdoor  Rug"
                | "Outdoor  Dining Chair"
                | "Outdoor Chair"
                | "Outdoor Coffee Table"
                | "Outdoor Dining Table"
                | "Outdoor Fire Pit"
                | "Outdoor Lounger"
                | "Outdoor Side Table"
                | "Outdoor Sofa"
                | "Outdoor Throw Pillow"
                | "Outdoor Umbrella";
              maxDepth?: number;
              maxHeight?: number;
              maxPrice?: number;
              maxWeight?: number;
              maxWidth?: number;
              minDepth?: number;
              minHeight?: number;
              minPrice?: number;
              minWeight?: number;
              minWidth?: number;
              name?: string;
            };
            sortOptions?: { index: "by_price"; order: "asc" | "desc" };
          },
          any
        >;
        getClientProductsByCategoryWithFilters: FunctionReference<
          "query",
          "public",
          {
            category:
              | "Arm Chair"
              | "Artwork"
              | "Baking Dish"
              | "Bamboo Flooring"
              | "Bar Cart"
              | "Bar Stool"
              | "Bar Table"
              | "Bath Linens"
              | "Bathroom Accessories"
              | "Bed"
              | "Bedding"
              | "Bedroom Vanity"
              | "Bench"
              | "Blind"
              | "Bookcase"
              | "Bowl"
              | "Broom"
              | "Brush"
              | "Cabinet"
              | "Can Opener"
              | "Carpet"
              | "Ceiling Lamp"
              | "Ceiling Mirror"
              | "Chaise Lounge"
              | "Chest"
              | "Coat Rack"
              | "Coffee Maker"
              | "Coffee Table"
              | "Colander"
              | "Concrete Flooring"
              | "Console Table"
              | "Cookie Sheet"
              | "Cookware"
              | "Cork Flooring"
              | "Corkscrew"
              | "Counter"
              | "Counter Stool"
              | "Cup"
              | "Curtain"
              | "Curtain Panels"
              | "Curtain Rod"
              | "Cutting Board"
              | "Desk"
              | "Desk Chair"
              | "Dining Chair"
              | "Dining Table"
              | "Dinnerware"
              | "Dresser"
              | "Dustpan"
              | "Engineered Wood"
              | "Entry Hook"
              | "Fixture"
              | "Floor Lamp"
              | "Fork"
              | "Grater"
              | "Hair Dryer"
              | "Hanger"
              | "Hardwood Flooring"
              | "Head Board"
              | "Iron"
              | "Ironing Board"
              | "Kettle"
              | "King Mattress"
              | "Kitchen Tool"
              | "Knife"
              | "Ladle"
              | "Laminate Flooring"
              | "Linoleum"
              | "Loveseat"
              | "Nightstand"
              | "Ottoman"
              | "Pancake Turner"
              | "Pendant Light"
              | "Pillow"
              | "Pitcher"
              | "Plant"
              | "Planter"
              | "Plate"
              | "Plunger"
              | "Potholder"
              | "Pots & Vases"
              | "Queen Mattress"
              | "Rack"
              | "Roast Pan"
              | "Rug"
              | "Rug Pad"
              | "Salad Plate"
              | "Salt & Pepper Shaker"
              | "Sconce"
              | "Screen"
              | "Sculpture"
              | "Sectional"
              | "Shelf"
              | "Shelving Unit"
              | "Side Table"
              | "Sideboard"
              | "Silverware Tray"
              | "Skillet"
              | "Small Appliance"
              | "Sofa"
              | "Sofa Bed"
              | "Sound Machine"
              | "Soup Bowl"
              | "Speaker Dock"
              | "Spoon"
              | "Standing Mirror"
              | "Stands"
              | "Stone Flooring"
              | "Storage Cabinet"
              | "Table Lamp"
              | "Tablecloth"
              | "Throw Blanket"
              | "Throw Pillow"
              | "Tile"
              | "Toaster"
              | "Tongs"
              | "Towel"
              | "Tray"
              | "Tumbler"
              | "TV"
              | "TV Media Console"
              | "TV Wall Mount"
              | "Twin Mattress"
              | "Utensils"
              | "Vanity"
              | "Vanity Light"
              | "Vegetable Peeler"
              | "Vinyl Flooring"
              | "Wall Mirror"
              | "Wallpaper"
              | "Wardrobe"
              | "Waste basket"
              | "Whisk"
              | "Wine Glass"
              | "Outdoor  Arm Chair"
              | "Outdoor  Rug"
              | "Outdoor  Dining Chair"
              | "Outdoor Chair"
              | "Outdoor Coffee Table"
              | "Outdoor Dining Table"
              | "Outdoor Fire Pit"
              | "Outdoor Lounger"
              | "Outdoor Side Table"
              | "Outdoor Sofa"
              | "Outdoor Throw Pillow"
              | "Outdoor Umbrella";
            paginationOptions?: { cursor?: string; numItems?: number };
            productFilter?: {
              availability?: "In Stock" | "Low Stock" | "Out of Stock";
              brand?: string;
              category?:
                | "Arm Chair"
                | "Artwork"
                | "Baking Dish"
                | "Bamboo Flooring"
                | "Bar Cart"
                | "Bar Stool"
                | "Bar Table"
                | "Bath Linens"
                | "Bathroom Accessories"
                | "Bed"
                | "Bedding"
                | "Bedroom Vanity"
                | "Bench"
                | "Blind"
                | "Bookcase"
                | "Bowl"
                | "Broom"
                | "Brush"
                | "Cabinet"
                | "Can Opener"
                | "Carpet"
                | "Ceiling Lamp"
                | "Ceiling Mirror"
                | "Chaise Lounge"
                | "Chest"
                | "Coat Rack"
                | "Coffee Maker"
                | "Coffee Table"
                | "Colander"
                | "Concrete Flooring"
                | "Console Table"
                | "Cookie Sheet"
                | "Cookware"
                | "Cork Flooring"
                | "Corkscrew"
                | "Counter"
                | "Counter Stool"
                | "Cup"
                | "Curtain"
                | "Curtain Panels"
                | "Curtain Rod"
                | "Cutting Board"
                | "Desk"
                | "Desk Chair"
                | "Dining Chair"
                | "Dining Table"
                | "Dinnerware"
                | "Dresser"
                | "Dustpan"
                | "Engineered Wood"
                | "Entry Hook"
                | "Fixture"
                | "Floor Lamp"
                | "Fork"
                | "Grater"
                | "Hair Dryer"
                | "Hanger"
                | "Hardwood Flooring"
                | "Head Board"
                | "Iron"
                | "Ironing Board"
                | "Kettle"
                | "King Mattress"
                | "Kitchen Tool"
                | "Knife"
                | "Ladle"
                | "Laminate Flooring"
                | "Linoleum"
                | "Loveseat"
                | "Nightstand"
                | "Ottoman"
                | "Pancake Turner"
                | "Pendant Light"
                | "Pillow"
                | "Pitcher"
                | "Plant"
                | "Planter"
                | "Plate"
                | "Plunger"
                | "Potholder"
                | "Pots & Vases"
                | "Queen Mattress"
                | "Rack"
                | "Roast Pan"
                | "Rug"
                | "Rug Pad"
                | "Salad Plate"
                | "Salt & Pepper Shaker"
                | "Sconce"
                | "Screen"
                | "Sculpture"
                | "Sectional"
                | "Shelf"
                | "Shelving Unit"
                | "Side Table"
                | "Sideboard"
                | "Silverware Tray"
                | "Skillet"
                | "Small Appliance"
                | "Sofa"
                | "Sofa Bed"
                | "Sound Machine"
                | "Soup Bowl"
                | "Speaker Dock"
                | "Spoon"
                | "Standing Mirror"
                | "Stands"
                | "Stone Flooring"
                | "Storage Cabinet"
                | "Table Lamp"
                | "Tablecloth"
                | "Throw Blanket"
                | "Throw Pillow"
                | "Tile"
                | "Toaster"
                | "Tongs"
                | "Towel"
                | "Tray"
                | "Tumbler"
                | "TV"
                | "TV Media Console"
                | "TV Wall Mount"
                | "Twin Mattress"
                | "Utensils"
                | "Vanity"
                | "Vanity Light"
                | "Vegetable Peeler"
                | "Vinyl Flooring"
                | "Wall Mirror"
                | "Wallpaper"
                | "Wardrobe"
                | "Waste basket"
                | "Whisk"
                | "Wine Glass"
                | "Outdoor  Arm Chair"
                | "Outdoor  Rug"
                | "Outdoor  Dining Chair"
                | "Outdoor Chair"
                | "Outdoor Coffee Table"
                | "Outdoor Dining Table"
                | "Outdoor Fire Pit"
                | "Outdoor Lounger"
                | "Outdoor Side Table"
                | "Outdoor Sofa"
                | "Outdoor Throw Pillow"
                | "Outdoor Umbrella";
              maxDepth?: number;
              maxHeight?: number;
              maxPrice?: number;
              maxWeight?: number;
              maxWidth?: number;
              minDepth?: number;
              minHeight?: number;
              minPrice?: number;
              minWeight?: number;
              minWidth?: number;
              name?: string;
            };
            sortOptions?: { index: "by_category_price"; order: "asc" | "desc" };
          },
          any
        >;
        getProductBrands: FunctionReference<
          "query",
          "public",
          {
            category?:
              | "Arm Chair"
              | "Artwork"
              | "Baking Dish"
              | "Bamboo Flooring"
              | "Bar Cart"
              | "Bar Stool"
              | "Bar Table"
              | "Bath Linens"
              | "Bathroom Accessories"
              | "Bed"
              | "Bedding"
              | "Bedroom Vanity"
              | "Bench"
              | "Blind"
              | "Bookcase"
              | "Bowl"
              | "Broom"
              | "Brush"
              | "Cabinet"
              | "Can Opener"
              | "Carpet"
              | "Ceiling Lamp"
              | "Ceiling Mirror"
              | "Chaise Lounge"
              | "Chest"
              | "Coat Rack"
              | "Coffee Maker"
              | "Coffee Table"
              | "Colander"
              | "Concrete Flooring"
              | "Console Table"
              | "Cookie Sheet"
              | "Cookware"
              | "Cork Flooring"
              | "Corkscrew"
              | "Counter"
              | "Counter Stool"
              | "Cup"
              | "Curtain"
              | "Curtain Panels"
              | "Curtain Rod"
              | "Cutting Board"
              | "Desk"
              | "Desk Chair"
              | "Dining Chair"
              | "Dining Table"
              | "Dinnerware"
              | "Dresser"
              | "Dustpan"
              | "Engineered Wood"
              | "Entry Hook"
              | "Fixture"
              | "Floor Lamp"
              | "Fork"
              | "Grater"
              | "Hair Dryer"
              | "Hanger"
              | "Hardwood Flooring"
              | "Head Board"
              | "Iron"
              | "Ironing Board"
              | "Kettle"
              | "King Mattress"
              | "Kitchen Tool"
              | "Knife"
              | "Ladle"
              | "Laminate Flooring"
              | "Linoleum"
              | "Loveseat"
              | "Nightstand"
              | "Ottoman"
              | "Pancake Turner"
              | "Pendant Light"
              | "Pillow"
              | "Pitcher"
              | "Plant"
              | "Planter"
              | "Plate"
              | "Plunger"
              | "Potholder"
              | "Pots & Vases"
              | "Queen Mattress"
              | "Rack"
              | "Roast Pan"
              | "Rug"
              | "Rug Pad"
              | "Salad Plate"
              | "Salt & Pepper Shaker"
              | "Sconce"
              | "Screen"
              | "Sculpture"
              | "Sectional"
              | "Shelf"
              | "Shelving Unit"
              | "Side Table"
              | "Sideboard"
              | "Silverware Tray"
              | "Skillet"
              | "Small Appliance"
              | "Sofa"
              | "Sofa Bed"
              | "Sound Machine"
              | "Soup Bowl"
              | "Speaker Dock"
              | "Spoon"
              | "Standing Mirror"
              | "Stands"
              | "Stone Flooring"
              | "Storage Cabinet"
              | "Table Lamp"
              | "Tablecloth"
              | "Throw Blanket"
              | "Throw Pillow"
              | "Tile"
              | "Toaster"
              | "Tongs"
              | "Towel"
              | "Tray"
              | "Tumbler"
              | "TV"
              | "TV Media Console"
              | "TV Wall Mount"
              | "Twin Mattress"
              | "Utensils"
              | "Vanity"
              | "Vanity Light"
              | "Vegetable Peeler"
              | "Vinyl Flooring"
              | "Wall Mirror"
              | "Wallpaper"
              | "Wardrobe"
              | "Waste basket"
              | "Whisk"
              | "Wine Glass"
              | "Outdoor  Arm Chair"
              | "Outdoor  Rug"
              | "Outdoor  Dining Chair"
              | "Outdoor Chair"
              | "Outdoor Coffee Table"
              | "Outdoor Dining Table"
              | "Outdoor Fire Pit"
              | "Outdoor Lounger"
              | "Outdoor Side Table"
              | "Outdoor Sofa"
              | "Outdoor Throw Pillow"
              | "Outdoor Umbrella";
            paginationOptions?: { cursor?: string; numItems?: number };
          },
          any
        >;
      };
    };
    user: {
      mutation: {
        updateUserById: FunctionReference<
          "mutation",
          "public",
          {
            updates: {
              authToken?: string;
              currentWorkspaceId?: Id<"workspaces">;
              email?: string;
              firstName?: string;
              fullName?: string;
              imageUrl?: string;
              lastLoginAt?: number;
              lastName?: string;
              phone?: string;
              updatedAt?: number;
            };
          },
          any
        >;
      };
      query: { getUser: FunctionReference<"query", "public", any, any> };
    };
    workspace: {
      asset: {
        query: {
          getWorkspaceAssets: FunctionReference<
            "query",
            "public",
            { workspaceId: Id<"workspaces"> },
            any
          >;
          getWorkspaceAssetsByType: FunctionReference<
            "query",
            "public",
            { type: "inspo" | "floorplan"; workspaceId: Id<"workspaces"> },
            any
          >;
        };
      };
      query: {
        getWorkspaceById: FunctionReference<
          "query",
          "public",
          { workspaceId: Id<"workspaces"> },
          any
        >;
        getUserWorkspaces: FunctionReference<"query", "public", any, any>;
      };
    };
    cart: {
      query: {
        getCartByWorkspaceId: FunctionReference<
          "query",
          "public",
          { workspaceId: Id<"workspaces"> },
          any
        >;
        getCartByDesignId: FunctionReference<
          "query",
          "public",
          { designId: Id<"designs">; workspaceId: Id<"workspaces"> },
          any
        >;
      };
      mutation: {
        saveCartItem: FunctionReference<
          "mutation",
          "public",
          {
            data: Array<{
              designId: Id<"designs">;
              productId: Id<"products">;
              quantity: number;
            }>;
            workspaceId: Id<"workspaces">;
          },
          any
        >;
        updateCartItem: FunctionReference<
          "mutation",
          "public",
          {
            cartItemId: Id<"cartItems">;
            updates: { productId?: Id<"products">; quantity?: number };
            workspaceId: Id<"workspaces">;
          },
          any
        >;
        deleteCartItem: FunctionReference<
          "mutation",
          "public",
          { cartItemId: Id<"cartItems">; workspaceId: Id<"workspaces"> },
          any
        >;
      };
    };
    chat: {
      mutation: {
        createChat: FunctionReference<
          "mutation",
          "public",
          { workspaceId: Id<"workspaces"> },
          any
        >;
      };
      query: {
        getChatUiMessagesAndUsers: FunctionReference<
          "query",
          "public",
          { chatId: Id<"chats">; workspaceId: Id<"workspaces"> },
          any
        >;
      };
    };
  };
};
export type InternalApiType = {};
