export const productCategories = [
  'Arm Chair',
  'Artwork',
  'Baking Dish',
  'Bamboo Flooring',
  'Bar Cart',
  'Bar Stool',
  'Bar Table',
  'Bath Linens',
  'Bathroom Accessories',
  'Bed',
  'Bedding',
  'Bedroom Vanity',
  'Bench',
  'Blind',
  'Bookcase',
  'Bowl',
  'Broom',
  'Brush',
  'Cabinet',
  'Can Opener',
  'Carpet',
  'Ceiling Lamp',
  'Ceiling Mirror',
  'Chaise Lounge',
  'Chest',
  'Coat Rack',
  'Coffee Maker',
  'Coffee Table',
  'Colander',
  'Concrete Flooring',
  'Console Table',
  'Cookie Sheet',
  'Cookware',
  'Cork Flooring',
  'Corkscrew',
  'Counter',
  'Counter Stool',
  'Cup',
  'Curtain',
  'Curtain Panels',
  'Curtain Rod',
  'Cutting Board',
  'Desk',
  'Desk Chair',
  'Dining Chair',
  'Dining Table',
  'Dinnerware',
  'Dresser',
  'Dustpan',
  'Engineered Wood',
  'Entry Hook',
  'Fixture',
  'Floor Lamp',
  'Fork',
  'Grater',
  'Hair Dryer',
  'Hanger',
  'Hardwood Flooring',
  'Head Board',
  'Iron',
  'Ironing Board',
  'Kettle',
  'King Mattress',
  'Kitchen Tool',
  'Knife',
  'Ladle',
  'Laminate Flooring',
  'Linoleum',
  'Loveseat',
  'Nightstand',
  'Ottoman',
  'Pancake Turner',
  'Pendant Light',
  'Pillow',
  'Pitcher',
  'Plant',
  'Planter',
  'Plate',
  'Plunger',
  'Potholder',
  'Pots & Vases',
  'Queen Mattress',
  'Rack',
  'Roast Pan',
  'Rug',
  'Rug Pad',
  'Salad Plate',
  'Salt & Pepper Shaker',
  'Sconce',
  'Screen',
  'Sculpture',
  'Sectional',
  'Shelf',
  'Shelving Unit',
  'Side Table',
  'Sideboard',
  'Silverware Tray',
  'Skillet',
  'Small Appliance',
  'Sofa',
  'Sofa Bed',
  'Sound Machine',
  'Soup Bowl',
  'Speaker Dock',
  'Spoon',
  'Standing Mirror',
  'Stands',
  'Stone Flooring',
  'Storage Cabinet',
  'Table Lamp',
  'Tablecloth',
  'Throw Blanket',
  'Throw Pillow',
  'Tile',
  'Toaster',
  'Tongs',
  'Towel',
  'Tray',
  'Tumbler',
  'TV',
  'TV Media Console',
  'TV Wall Mount',
  'Twin Mattress',
  'Utensils',
  'Vanity',
  'Vanity Light',
  'Vegetable Peeler',
  'Vinyl Flooring',
  'Wall Mirror',
  'Wallpaper',
  'Wardrobe',
  'Waste basket',
  'Whisk',
  'Wine Glass',
  'Outdoor Arm Chair',
  'Outdoor Rug',
  'Outdoor Dining Chair',
  'Outdoor Chair',
  'Outdoor Coffee Table',
  'Outdoor Dining Table',
  'Outdoor Fire Pit',
  'Outdoor Lounger',
  'Outdoor Side Table',
  'Outdoor Sofa',
  'Outdoor Throw Pillow',
  'Outdoor Umbrella',
] as const;

export const productStyles = [
  'Art Deco',
  'Biophilic',
  'Bohemian',
  'Brutalism',
  'Coastal',
  'Colonial',
  'Contemporary',
  'Craftsman',
  'Eclectic',
  'French Country',
  'Hollywood Glamour',
  'Industrial',
  'Japandi',
  'Luxury',
  'Maximalist',
  'Mediterranean',
  'Mid-Century Modern',
  'Minimalist',
  'Modern',
  'Modern Farmhouse',
  'Neoclassical',
  'Neutral',
  'Rustic',
  'Scandinavian',
  'Shabby Chic',
  'Southwestern',
  'Traditional',
  'Transitional',
  'Tudor',
  'Victorian',
  'Vintage',
] as const;
